### ISSUE TITLE
Texture files simply missing, mainly for MS-III, Saturn III parts, and all Russian Parts, as well as a few others.

### ISSUE THREAD

**Issue by MLRocketScience** [Katniss218/KatnisssPartsPack#2]
As above, some parts are simply missing their .png texture files. I've seen those parts with textures in your reddit posts/videos, so I'd have to assume they just got left out? If you still have them, could you put them on here?

**Comment by Katniss218** [comment]
Yeah, that's just me being lazy with the textures. Doesn't help that I haven't really touched KSP in the last month or so.
