### ISSUE TITLE
Files are seprated

### ISSUE THREAD

**Issue by Kspenjoyer11323** [Katniss218/KatnisssPartsPack#5]
Im not sure if i just dont know how to download these files but they are all separate. When i try to download the files they are all in their component parts like instead of being just the entire file it would say j-2_engine or something like that.

**Comment by Katniss218** [comment]
You need to click "code" (green colored button) and "download zip" from the dropdown, then use the contents of "GameData" folder inside the zip you downloaded.

There's also a bunch of dev stuff in "raw" (for people who want to edit 3D models/textures).
